package runix.temporal.condition

import runix.temporal.trackers.CategoricalTracker
import runix.temporal.trackers.TrackerProvider
import kotlin.time.Duration

/**
 * Internal sealed hierarchy of declarative Categorical signal conditions.
 *
 * These apply to signal types like enums or strings, where identity and transitions
 * are more important than numeric value.
 *
 * Each condition defines a retention window and compiles itself into a [TemporalExpression],
 * using a tracker registered under the given [key].
 *
 * These types are generated by the DSL but used only by the engine.
 */
internal sealed interface CategoricalConditionType : ConditionType

/**
 * Condition is true if the latest value matches the expected state.
 * This is an instantaneous equality check.
 */
internal data class IsInState<T>(
    val expected: T
) : CategoricalConditionType {
    override val retention = Duration.ZERO

    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluateLatestPersisted({ it == expected }, Duration.ZERO)
        }
    }
}

/**
 * Condition is true if the signal has persisted in [expected] state for at least [retention].
 */
internal data class PersistedInState<T>(
    val expected: T,
    override val retention: Duration
) : CategoricalConditionType {
    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluateLatestPersisted({ it == expected }, retention)
        }
    }
}

/**
 * Condition is true if the signal has ever been in the [expected] state within retention.
 */
internal data class WasEverInState<T>(
    val expected: T,
    override val retention: Duration
) : CategoricalConditionType {
    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluatePastTransition({ _, curr -> curr == expected }, Duration.ZERO)
        }
    }
}

/**
 * Condition is true if the signal was in [expected] state for at least [retention] at some point.
 */
internal data class WasInStateFor<T>(
    val expected: T,
    val forDuration: Duration,
    val inLast: Duration
) : CategoricalConditionType {
    override val retention = inLast

    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluatePastTransition({ prev, _ -> prev == expected }, forDuration)
        }
    }
}

/**
 * Condition is true if the signal transitioned through the exact sequence of [states], in order.
 */
internal data class TransitionedThrough<T>(
    val states: List<T>,
    val inLast: Duration
) : CategoricalConditionType {
    override val retention = inLast
    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluateTransitionSequence(states)
        }
    }
}

/**
 * Condition is true if the signal transitioned to [expected]
 * within the last [inLast] duration and stayed in that state for at least [forDuration].
 *
 * - If [forDuration] is `Duration.ZERO`, this models a momentary transition.
 * - If [forDuration] > 0, the state must have held for that long after transition.
 */
internal data class TransitionedTo<T>(
    val expected: T,
    val forDuration: Duration = Duration.ZERO,
    val inLast: Duration
) : CategoricalConditionType {

    override val retention = inLast

    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluatePastTransition({ _, curr -> curr == expected }, forDuration)
        }
    }
}

/**
 * Condition is true if the signal transitioned away from [expected]
 * within the last [inLast] duration and remained in a different state for at least [forDuration].
 *
 * - If [forDuration] is `Duration.ZERO`, this models a momentary departure.
 * - If [forDuration] > 0, the state must have held after leaving [expected].
 */
internal data class TransitionedFrom<T>(
    val from: T,
    val forDuration: Duration = Duration.ZERO,
    val inLast: Duration
) : CategoricalConditionType {

    override val retention = inLast

    override fun compileExpression(key: String, provider: TrackerProvider): TemporalExpression {
        @Suppress("UNCHECKED_CAST")
        return {
            val tracker = provider.getCategoricalTracker(key) as CategoricalTracker<T>
            tracker.evaluatePastTransition({ prev, _ -> prev == from }, forDuration)
        }
    }
}
